version: "3.3"
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=s3,lambda,dynamodb
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
    networks:
      - local_network

  data_simulator:
    build: https://github.com/distributed-analytics-system/DistributedSystem-DataSimulator.git
    container_name: data_simulator
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      PORT: 8080
      LOG_LEVEL: info
      DATA_RECEIVER_BASE_URL: http://data_receiver:8081
    networks:
      - s_to_s_network

  data_receiver:
    build: https://github.com/distributed-analytics-system/DistributedSystem-DataReceiver.git
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: development
      container_name: data_receiver
      PORT: 8081
      DD_AGENT_HOST: empty
      LOG_LEVEL: info
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://localstack:4566
      AWS_S3_BUCKET_NAME: distributed-analytics-system
    networks:
      - local_network
      - s_to_s_network

  data_processor:
    build: https://github.com/distributed-analytics-system/DistributedSystem-DataProcessor.git
    environment:
      NODE_ENV: development
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://localstack:4566
      AWS_S3_BUCKET_NAME: distributed-analytics-system
    networks:
      - local_network

  data_analyzer:
    build: https://github.com/distributed-analytics-system/DistributedSystem-DataAnalyzer.git
    ports:
      - "8082:8082"
    environment:
      NODE_ENV: development
      PORT: 8082
      DD_AGENT_HOST: empty
      LOG_LEVEL: info
      AWS_REGION: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT: http://localstack:4566
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
  s_to_s_network:
    driver: bridge
